CREATE TABLE USERS (
  ID       INT8 AUTO_INCREMENT PRIMARY KEY        NOT NULL,
  NAME     VARCHAR(50)                            NOT NULL,
  EMAIL    VARCHAR(64)                            NOT NULL,
  ENABLED  BOOL                                   NOT NULL,
  PASSWORD VARCHAR(256)                           NOT NULL,
);

CREATE TABLE USER_ROLE (
  ID   INT8 AUTO_INCREMENT PRIMARY KEY         NOT NULL,
  ROLE VARCHAR(255) UNIQUE                     NOT NULL,
);

CREATE TABLE USERS_USER_ROLE (
  USER_ID INT8 NOT NULL,
  ROLE_ID INT8 NOT NULL,
  FOREIGN KEY (ROLE_ID) REFERENCES USER_ROLE (ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE VERIFICATION_TOKEN (
  TOKEN       VARCHAR(256) PRIMARY KEY NOT NULL,
  EXPIRY_DATE TIMESTAMP(6)             NOT NULL,
  VERIFIED    BOOL,
  USER_ID     INT8                     NOT NULL,

  FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE OAUTH_CLIENT_DETAILS (
  CLIENT_ID               VARCHAR(256) PRIMARY KEY,
  RESOURCE_IDS            VARCHAR(256),
  CLIENT_SECRET           VARCHAR(256),
  SCOPE                   VARCHAR(256),
  AUTHORIZED_GRANT_TYPES  VARCHAR(256),
  WEB_SERVER_REDIRECT_URI VARCHAR(256),
  AUTHORITIES             VARCHAR(256),
  ACCESS_TOKEN_VALIDITY   INTEGER,
  REFRESH_TOKEN_VALIDITY  INTEGER,
  ADDITIONAL_INFORMATION  VARCHAR(4096),
  AUTOAPPROVE             VARCHAR(256)
);

CREATE TABLE OAUTH_CLIENT_TOKEN (
  TOKEN_ID          VARCHAR(256),
  TOKEN             LONGVARBINARY,
  AUTHENTICATION_ID VARCHAR(256) PRIMARY KEY,
  USER_NAME         VARCHAR(256),
  CLIENT_ID         VARCHAR(256)
);

CREATE TABLE OAUTH_ACCESS_TOKEN (
  TOKEN_ID          VARCHAR(256),
  TOKEN             LONGVARBINARY,
  AUTHENTICATION_ID VARCHAR(256) PRIMARY KEY,
  USER_NAME         VARCHAR(256),
  CLIENT_ID         VARCHAR(256),
  AUTHENTICATION    LONGVARBINARY,
  REFRESH_TOKEN     VARCHAR(256)
);

CREATE TABLE OAUTH_REFRESH_TOKEN (
  TOKEN_ID       VARCHAR(256),
  TOKEN          LONGVARBINARY,
  AUTHENTICATION LONGVARBINARY
);

CREATE TABLE OAUTH_CODE (
  CODE           VARCHAR(256),
  AUTHENTICATION LONGVARBINARY
);

CREATE TABLE OAUTH_APPROVALS (
  USERID         VARCHAR(256),
  CLIENTID       VARCHAR(256),
  SCOPE          VARCHAR(256),
  STATUS         VARCHAR(10),
  EXPIRESAT      TIMESTAMP,
  LASTMODIFIEDAT TIMESTAMP
);

-- CUSTOMIZED OAUTH_CLIENT_DETAILS TABLE
CREATE TABLE CLIENTDETAILS (
  APPID                  VARCHAR(256) PRIMARY KEY,
  RESOURCEIDS            VARCHAR(256),
  APPSECRET              VARCHAR(256),
  SCOPE                  VARCHAR(256),
  GRANTTYPES             VARCHAR(256),
  REDIRECTURL            VARCHAR(256),
  AUTHORITIES            VARCHAR(256),
  ACCESS_TOKEN_VALIDITY  INTEGER,
  REFRESH_TOKEN_VALIDITY INTEGER,
  ADDITIONALINFORMATION  VARCHAR(4096),
  AUTOAPPROVESCOPES      VARCHAR(256)
);
